# Generated by Django 4.2.3 on 2023-07-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
                ('describtion', models.TextField(blank=True)),
                ('first_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('second_image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('third_image', models.ImageField(blank=True, null=True, upload_to='products')),
            ],
        ),
    ]
