# Generated by Django 4.2.3 on 2023-07-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_products_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.BooleanField(default=True),
        ),
    ]
